[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Compat]]
git-tree-sha1 = "e891dc2ba653107604985bc5ab7294d9de83630f"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.66.0"

    [Compat.deps]
    Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
    Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
    DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
    Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
    InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
    IterativeEigensolvers = "de555fa4-b82f-55e7-8b71-53f60bbc027d"
    LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
    Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
    LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
    Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
    Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
    Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
    Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
    REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
    Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
    Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
    SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
    Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
    SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
    SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
    UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
    Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[DataStructures]]
deps = ["Compat", "REPL"]
git-tree-sha1 = "abc05631fbe6e6a62c60f37bf644df87d5470fe4"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.8.3"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IterativeEigensolvers]]
uuid = "de555fa4-b82f-55e7-8b71-53f60bbc027d"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "6b89303a6f9dbdfbcaec5eb2d985582903a61474"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.0"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Pkg3]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["Compat", "LinearAlgebra", "Random", "Test"]
git-tree-sha1 = "6c0c5902c84cc4a5066052c9089eed5f5f2c794c"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.7.0"

[[SuiteSparse]]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
