name = "Yao"
uuid = "5872b779-8223-5990-8dd0-5abbb0748c8c"
version = "0.8.11"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
YaoAPI = "0843a435-28de-4971-9e8b-a9641b2983a8"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
YaoSym = "3b27209a-d3d6-11e9-3c0f-41eb92b2cb9d"

[compat]
BitBasis = "0.8"
LinearAlgebra = "1"
LuxurySparse = "0.7"
Reexport = "1"
YaoAPI = "0.4"
YaoArrayRegister = "0.9"
YaoBlocks = "0.13"
YaoSym = "0.6"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra", "Documenter", "Random", "SymEngine"]
