name = "YaoSym"
uuid = "3b27209a-d3d6-11e9-3c0f-41eb92b2cb9d"
version = "0.4.2"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"
YaoBase = "a8f54c17-34bc-5a9d-b050-f522fe3f755f"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"

[compat]
BitBasis = "0.6"
LuxurySparse = "0.5, 0.6"
Requires = "1.0"
SymEngine = "0.7"
YaoArrayRegister = "0.6"
YaoBase = "0.13"
YaoBlocks = "0.8, 0.9, 0.10"
julia = "1"

[extras]
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SymEngine"]
