name = "YaoPlots"
uuid = "32cfe2d9-419e-45f2-8191-2267705d8dbc"
version = "0.2.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
ZXCalculus = "3525faa3-032d-4235-a8d4-8c2939a218dd"

[compat]
Colors = "0.12"
Compose = "0.9"
GraphPlot = "0.4"
LightGraphs = "1.3"
ZXCalculus = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
