name = "Yao"
uuid = "1bc31baa-972f-11e8-31dd-c182aaa973df"
authors = ["Roger-luo <hiroger@qq.com>", "GiggleLiu <cacate0129@gmail.com>"]
version = "0.2.0"

[deps]
CacheServers = "a921213e-d44a-5460-ac04-5d720a99ba71"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Expokit = "a1e7a1ef-7a5d-5822-a38c-be74e1bb89f4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
LuxurySparse = "72cad168-9621-11e8-1b1e-73228c0c6ca7"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
