name = "QuAlgorithmZoo"
uuid = "65c24e16-9b0a-11e8-1353-efc5bc5f6586"
authors = ["Roger-luo <hiroger@qq.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
