name = "YaoBlocks"
uuid = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
version = "0.7.3"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
CacheServers = "a921213e-d44a-5460-ac04-5d720a99ba71"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LegibleLambdas = "f1f30506-32fe-5131-bd72-7c197988f9e5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"
YaoBase = "a8f54c17-34bc-5a9d-b050-f522fe3f755f"

[compat]
BitBasis = "~0.6"
CacheServers = "~0.2"
ExponentialUtilities = "~1.5"
LegibleLambdas = "~0.2"
LuxurySparse = "~0.5"
MLStyle = "~0.3"
SimpleTraits = "~0.9"
StaticArrays = "~0"
StatsBase = "~0"
YaoArrayRegister = "~0.5.0"
YaoBase = "~0.11.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
