[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"
YaoBase = "a8f54c17-34bc-5a9d-b050-f522fe3f755f"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
