[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DocThemeIndigo = "8bac0ac5-51bf-41f9-885e-2bf1ac2bec5f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoAPI = "0843a435-28de-4971-9e8b-a9641b2983a8"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
YaoPlots = "32cfe2d9-419e-45f2-8191-2267705d8dbc"
YaoSym = "3b27209a-d3d6-11e9-3c0f-41eb92b2cb9d"
YaoToEinsum = "9b173c7b-dc24-4dc5-a0e1-adab2f7b6ba9"
ZXCalculus = "3525faa3-032d-4235-a8d4-8c2939a218dd"
